serviceMonitor:
  metadata:
    labels:
      release: prometheus
podMonitor:
  metadata:
    labels:
      release: prometheus
prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3-default
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
grafana:
  persistence:
    enabled: true
    storageClassName: gp3-default
    size: 10Gi
