loki:
  serviceMonitor:
    enabled: true
  persistence:
    enabled: true
    storageClassName: gp3-default
    size: 10Gi

promtail:
  config:
    snippets:
      extraRelabelConfigs:
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: log_type
          action: replace
          regex: istio-proxy
          replacement: envoy
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: log_type
          action: replace
          regex: .+
          replacement: application
