base:
  # valores para istio-base si los necesitas

istiod:
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: jaeger
        opentelemetry:
          port: 4317
          service: jaeger-collector.istio-system.svc.cluster.local
